# Generated by Django 4.1.5 on 2023-01-06 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='copmlete',
            new_name='complete',
        ),
    ]
